### ISSUE TITLE
Update to Bootstrap 5

### ISSUE THREAD

**Issue by ms609** [ms609/TreeTools#164]
```yaml
  bootstrap: 5
  bslib:
    danger: "#A6081A" # Accessibility suggestion
```

Also add search to `right` of navbar, before `github`

Add equivalent issue to other repos
